version: "3"
services:
  serverApp:
    image: sgp-spring-docker
    ports:
      - 8082:8080
    depends_on: 
      - db
  db:
    image: mongo
    volumes:
      - ./database:/data/db
    ports:
      - 27018:27017
  clientApp:
    image: sgp-react-docker
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true